### ISSUE TITLE
Failed to send the job. (SSL peer certificate or SSH remote key was not OK)

### ISSUE THREAD

**Issue by donatocl** [Lihis/ets2-job-logger#15]
I have SSL runing on API URL, with Sectigo Limited cert installed. I was checking on google and is related to CURLOPT_SSL_VERIFYPEER or CURLOPT_SSL_VERIFYHOST. But is weird, because the SSL installed is valid.

**Comment by Lihis** [comment]
`libcurl` pulled via Conan is using OpenSSL and certificates from system are not being used. Easiest way to fix this would be to have a `libcurl` which build with `with_winssl`. Second option would be to add code to load certificates manually on Windows..

So for "easy" fix, in `conanfile.txt` add:
```
[options]
libcurl:with_openssl=False
libcurl:with_winssl=True
```

And then do the usual `conan install` but also append `--build libcurl` to the command as pre-built package does not seem to be available.

**Comment by donatocl** [comment]
#18 this fixed the problem.
