### ISSUE TITLE
Error with some lang encode or similar

### ISSUE THREAD

**Issue by donatocl** [Lihis/ets2-job-logger#19]
When you open the application, a weird simbols appears in the income display option.
Image attached, this also happen when some cities have names with some characters.
![2020-01-21 15_08_15-Window](https://user-images.githubusercontent.com/58643272/72830762-2eec8180-3c60-11ea-8041-5a218f42b75e.png)

**Comment by Lihis** [comment]
Maybe [wxS()](https://docs.wxwidgets.org/3.0/group__group__funcmacro__string.html#ga0a06701ea0e6bb00c5171ace1b1f5691) should be used in [here](https://github.com/Lihis/ets2-job-logger/blob/4aac0a4df48fc61ddee9fbb63c3d14c0b59153fd/gui/MainWindow.cpp#L84)? Open a pull request when you find the solution.

**Comment by donatocl** [comment]
I will try to find a solution!

**Comment by donatocl** [comment]
> 
> 
> Maybe [wxS()](https://docs.wxwidgets.org/3.0/group__group__funcmacro__string.html#ga0a06701ea0e6bb00c5171ace1b1f5691) should be used in [here](https://github.com/Lihis/ets2-job-logger/blob/4aac0a4df48fc61ddee9fbb63c3d14c0b59153fd/gui/MainWindow.cpp#L84)? Open a pull request when you find the solution.

In what part of the line I need to put the wxS()? I can test now, also this happen with origin and destination some times, for some reason in the gui (and when the job is sent) appears something like "??????" in origin because the name of origin have special characters, so maybe the same solution that you explain here need to be applied for origin and destination.

Please let me know where I need to put that and I will test now.

Thanks!

**Comment by Lihis** [comment]
So `L" €"` would be `wxS("€")`.

Which language you have set in the game?

**Comment by donatocl** [comment]
In the game I use Spanish.
tha line modified:
` m_lblIncome->SetLabel(wxString(std::to_string(m_job.income)).append(**wxS(" €")**));`
Still appears as unknown character in gui

**Comment by Lihis** [comment]
I resorted to test with Finnish; Finnish and Cyrillic alphabets are display correctly (on Linux).

You'll probably have to study about [Unicode Support](https://docs.wxwidgets.org/3.0/overview_unicode.html) in wxWidgets. According the SCS SDK documentation [scs_value_string_t](https://github.com/Lihis/scs-sdk/blob/master/include/scs/scssdk_value.h#L73) is encoded in UTF-8. wxWidgets provided by Conan should have Unicode support [enabled](https://github.com/bincrafters/conan-wxwidgets/blob/testing/3.1.3/conanfile.py#L67).

**Comment by donatocl** [comment]
This happen per example with your name in "About" the "ä" appears as
unknown character.

**Comment by Lihis** [comment]
Hard to say what to do as I don't have Windows and "it works on my machine" :)

Google is your friend. This [issue](https://trac.wxwidgets.org/ticket/18113) looks similar to our case.

**Comment by donatocl** [comment]
My bad, I try again with Poznan city "Poznań" and now its working fine!

**Comment by Lihis** [comment]
So the € character fixed itself? Same for ä?

**Comment by donatocl** [comment]
My bad, is fixed using wxString::FromUTF8()
