### ISSUE TITLE
Special Transports don't send job accepted

### ISSUE THREAD

**Issue by Subtixx** [Lihis/ets2-job-logger#24]
In my ATS installation special transports don't send a request to v1/job with status 1 when accepting. Only when delivering with status 3. Havent tested cancelling

Also the UI shows nothing:
![pic](https://user-images.githubusercontent.com/20743379/73613676-5c3e1580-45f8-11ea-9ff5-c45c6fe1a84e.png)

Ingame:
![](https://i.imgur.com/U6JN6Fy.png)

**Comment by Lihis** [comment]
This confirms #13 so closing this as duplicate.
