### ISSUE TITLE
Option to disable /truck endpoint

### ISSUE THREAD

**Issue by Subtixx** [Lihis/ets2-job-logger#25]
There should be a setting to disable sending to /truck endpoint. Because it can be quite the overhead the for API endpoint even when its not implemented

**Comment by Lihis** [comment]
Probably not a setting as users could leave it on anyway. Maybe when program is started query the server of it's capabilities? E.g. `v1/capabilities`:

```
{
    "truck": false
}
```

Maybe overkill as I don't know will there be other information which would be sent as frequently as truck position..

**Comment by Subtixx** [comment]
This would be even better :)

**Comment by donatocl** [comment]
And if the program is executed and the computer does not have internet, but after opening it, it connects to the Wi-Fi, for example, in this case, what option will it take by default? send or not send anything? Or will you continue trying to consult the webapi until you connect?

**Comment by Subtixx** [comment]
Default should always be on. And yes retry until a request was successful.

**Comment by Lihis** [comment]
Can you comment to the pull request?

**Comment by Subtixx** [comment]
What do you mean?
