### ISSUE TITLE
Send the cargo_model_id information in the JSON post

### ISSUE THREAD

**Issue by donatocl** [Lihis/ets2-job-logger#34]
Is possible to send the cargo_model_id? with this, on web-side I can identify is this correspond to a refrigerated job, etc.

The value in sdk is called cargo_model_id (I think).

Thank you!

**Comment by Lihis** [comment]
There is no references to "model" in SDK, Cargo ID is already in the JSON, I need more specific details.

**Comment by Subtixx** [comment]
There was/is a way though
https://github.com/nlhans/ets2-sdk-plugin/blob/8c516a40cd757b3aa647e2df549d44fdf8ef428a/ets2-telemetry/inc/scs_config_handlers.hpp#L25

**Comment by Lihis** [comment]
That is a truck model?

**Comment by donatocl** [comment]
Is scsConfigHandle(TrailerId); and scsConfigHandle(TrailerName); I think, im searching to have the trailer model or type, is like scs_flatbed or scs_refeer, etc.

**Comment by Lihis** [comment]
Included this in #37. About truck information create a new issue and explain briefly how it should be sent or structured in the JSON.
