### ISSUE TITLE
More infos when job delievered

### ISSUE THREAD

**Issue by Subtixx** [Lihis/ets2-job-logger#35]
Mainly those:

>  * li revenue
>  * li earned_xp
>  * li delivery_time
>  * li autopark_used
>  * li autoload_used

https://github.com/Lihis/scs-sdk/blob/5b2bf461c98731687c508ef85e2082da213e5aee/include/scs/common/scssdk_telemetry_common_gameplay_events.h#L21-L33

Especiall this is quite important
> job_market

https://github.com/Lihis/scs-sdk/blob/922fb3a7ac271d8ec079654bf2449fb2abf103b7/include/scs/common/scssdk_telemetry_common_configs.h#L142

**Comment by donatocl** [comment]
@Subtixx the job_market what info send? (just to know)

**Comment by Subtixx** [comment]
job_market is where the job was accepted

**Comment by Lihis** [comment]
Created PR #37 I would appreciate if you guys used the Review functionality to review it, leave comments if something should changed or approve it if it looks good for you.
