### ISSUE TITLE
Send truck information in JSON post

### ISSUE THREAD

**Issue by donatocl** [Lihis/ets2-job-logger#38]
Hi,

If is possible, will be great to get truck information used in the job like id, name, brand_name, brand_id and wheel_count in JSON format example:

"truck": {
    "id": "[@li id](https://github.com/Lihis/scs-sdk/blob/922fb3a7ac271d8ec079654bf2449fb2abf103b7/include/scs/common/scssdk_telemetry_common_configs.h#L67)",
    "name": "[@li name](https://github.com/Lihis/scs-sdk/blob/922fb3a7ac271d8ec079654bf2449fb2abf103b7/include/scs/common/scssdk_telemetry_common_configs.h#L68)",
    "wheel_count": "[@li wheel_count](https://github.com/Lihis/scs-sdk/blob/922fb3a7ac271d8ec079654bf2449fb2abf103b7/include/scs/common/scssdk_telemetry_common_configs.h#L88)",
    "brand_name": "[@li brand](https://github.com/Lihis/scs-sdk/blob/922fb3a7ac271d8ec079654bf2449fb2abf103b7/include/scs/common/scssdk_telemetry_common_configs.h#L66)",
    "brand_id": "[@li brand_id](https://github.com/Lihis/scs-sdk/blob/922fb3a7ac271d8ec079654bf2449fb2abf103b7/include/scs/common/scssdk_telemetry_common_configs.h#L65)"
}

Thank you a lot!

**Comment by donatocl** [comment]
Continue in #37

**Comment by Lihis** [comment]
Not fixed yet, re-opening.

**Comment by donatocl** [comment]
Done thanks to @Lihis !
