### ISSUE TITLE
Bincrafters infrastructure changes

### ISSUE THREAD

**Issue by Lihis** [Lihis/ets2-job-logger#50]
Bincrafters announced infrastructural changes which require manual action: https://bincrafters.github.io/2020/04/19/infrastructure-changes-and-required-actions/.

This has broken Windows build. Some work done to fix the build is in [fix-windows-build](https://github.com/Lihis/ets2-job-logger/tree/fix-windows-build) branch but help would be appreciated.

**Comment by ResTedRU** [comment]
Was also updated SCS SDK to 1.13 https://modding.scssoft.com/wiki/Documentation/Engine/SDK/Telemetry
