### ISSUE TITLE
Adding steam_api sdk

### ISSUE THREAD

**Issue by meatlayer** [Lihis/ets2-job-logger#55]
Hello.

It may be possible to add [steam_api sdk](https://partner.steamgames.com/doc/sdk/api#2) to get the username and Steam_ID of the user trucking the cargo in the json data? I think this could be helpful, especially for those who would like to add accounting for cargo transportation to their site through Steam authorization.

<details>
  <summary>As example</summary>
  
  **"SteamUsername": "DT ML",
  "SteamID": "76561198037140422",**
  
  ```
{
  "autoLoad": true,
  "autoPark": true,
  "SteamUsername": "DT ML",
  "SteamID": "76561198037140422",
  "cargo": {
    "damage": 0.016597917303442955,
    "id": "gifts",
    "mass": 23560,
    "name": "Подарки"
  },
  "destination": {
    "city": {
      "id": "coimbra",
      "name": "Coimbra"
    },
    "company": {
      "id": "agregados",
      "name": "Agregados,_S_A_"
    }
  },
  "distance": {
    "driven": 220,
    "planned": 218
  },
  "fuelConsumed": 71.85861206054688,
  "game": "ets2",
  "income": 15314,
  "isSpecial": false,
  "maxSpeed": 26.356029510498047,
  "revenue": 14289,
  "source": {
    "city": {
      "id": "vigo",
      "name": "Vigo"
    },
    "company": {
      "id": "trans_cab",
      "name": "Transportes_Caballería"
    }
  },
  "status": 3,
  "time": 20,
  "trailer": {
    "accessoryId": "",
    "id": "scs_box_dry_van_event_chassis_eventx2esii"
  },
  "truck": {
    "brand": {
      "id": "scania",
      "name": "Scania"
    },
    "id": "vehicle_scania_s_2016",
    "name": "S",
    "wheels": 4
  },
  "type": 4,
  "xp": 198
}
  ```
  
</details>

**Comment by Lihis** [comment]
If you are implementing Steam authorization on your website, why can't you link an user to an Steam ID, just like you link an payload to an user?

**Comment by meatlayer** [comment]
How? 
It is necessary to somehow identify each cargo with each user. The data in json cannot be correlated with any user at the moment.
That is, in the json data there is no user name, no user ID, nothing at all. For this reason, it is impossible to understand who exactly trucking the cargo, me or my friends who installed ets2-job-logger and configured the URL API to my site.

When it will be possible to identify each transported cargo, it may be easier to do authorization through steam on web-site, firstly, and secondly, it will be possible to create statistics among familiar friends in the site database by username/profile or create a bot for discord, which will send data to the general group about which of the participants trucking job cargo.

**Comment by Lihis** [comment]
Every payload contains the user API key in `Authorization-token` [header](https://github.com/Lihis/ets2-job-logger/blob/2b401c404834455a4e6a0d39d32fd81d08589ca6/gui/Logger/JobSender.cpp#L332). Seems that it's missing from the documentation, I'll try to push the refactored documentation out..

**Comment by Lihis** [comment]
The API key is now [documented](https://github.com/Lihis/ets2-job-logger/blob/master/docs/API.md). It needs still some rephrasing and I'm still thinking should the program enforce a sane minimum length for the key.

Closing via b0ab9fa854acaa71ed5789d446b9060cf96df96c.
