### ISSUE TITLE
Plugin file missing

### ISSUE THREAD

**Issue by donatocl** [Lihis/ets2-job-logger#6]
![2019-12-17 01_48_59-win_x64](https://user-images.githubusercontent.com/58643272/70965722-74b99700-206f-11ea-92af-c498fc0bb98e.png)

![2019-12-17 01_48_20-win_x64](https://user-images.githubusercontent.com/58643272/70965688-5bb0e600-206f-11ea-90ec-31405e579d12.png)
I have one folder called joblogger, inside the .exe and .dll. I double clic on .exe and check install ETS2, browse the path steamapps/common/EuroTruck Simulator 2/. I put the api url and api key, then I press OK and error apears "Plugin file missing" and from there, every time when I double clic on .exe say the same and close.

I tried also to put the both files inside win_x64 but still the same error

**Comment by Lihis** [comment]
First of all, you don't need to copy the `ets2-job-logger.exe` to anywhere from build directory, it can be wherever (maybe it could be installed via installer to `Program Files`).

Only requirement is that directory structure is like this:
```
|-- C:\Users\<USER>\long\path\to\build\directory
|-- | -- ets2-job-logger.exe
|-- | -- win_x64\
|-- | -- | ets2-job-logger.dll
```

**Comment by donatocl** [comment]
But I dont have the game inside the same pc, is another pc, so I move the files, you mean that I need to have the build directory to run the app?

**Comment by donatocl** [comment]
I have this structure and dont work:
|-- C:\Users\Donato\ets2logger\
|-- | -- ets2-job-logger.exe
|-- | -- win_x64\
|-- | -- | ets2-job-logger.dll

Still saying about file missing

**Comment by Lihis** [comment]
Build directory is not needed. That directory structure looks good.

What you could test is change this [line](https://github.com/Lihis/ets2-job-logger/blob/master/gui/Logger/PluginInstaller.cpp#L163) with this:
```
error = "Plugin file missing, check your program installation. " + pluginFile;
```

Then in the error dialog there should also be the path to the plugin, e.g. `C:\Users\Donato\ets2logger\win_x64\ets2-job-logger.dll`.

**Comment by donatocl** [comment]
In the file PluginInstaller.cpp on line 110, there is "path.append(**R**"(\bin\win_x64\)");" that R is correct?

**Comment by donatocl** [comment]
Here is the response when adding the + pluginFile
![2019-12-17 05_09_14-test1](https://user-images.githubusercontent.com/58643272/70976873-814be880-208b-11ea-9b49-9f4129844d6a.png)

**Comment by Lihis** [comment]
That's why it can't find the plugin..

This [line](https://github.com/Lihis/ets2-job-logger/blob/master/gui/Logger/PluginInstaller.cpp#L93) should be:
```
path.append(wxFileName::GetPathSeparator() + "ets2-job-logger" + get_plugin_extension(platform));
```

**Comment by donatocl** [comment]
With that change, now the build fail.

https://pastebin.com/dWK56unj

**Comment by Lihis** [comment]
> In the file PluginInstaller.cpp on line 110, there is "path.append(R"(\bin\win_x64)");" that R is correct?

Yes that is correct, it is a raw string literal.

Created new PR which should fix this issue.

**Comment by donatocl** [comment]
That fixed the problem!
