### ISSUE TITLE
error in api truck and new release

### ISSUE THREAD

**Issue by voignar** [Lihis/ets2-job-logger#62]
I am using version v0.1.0-alpha3 but I have seen that it is almost 2 years old and in this time there have been changes. When collecting the information on my api server I get the following error

`[client 95.61.249.194] ModSecurity: Warning. Pattern match "(?i:(?:[\\"'`]\\\\s*?\\\\*.+(?:x?or|div|like|between|and|id)\\\\W*?[\\"'`]\\\\d)|(?:\\\\^[\\"'`])|(?:^[\\\\w\\\\s\\"'`-]+(?<=and\\\\s)(?<=or|xor|div|like|between|and\\\\s)(?<=xor\\\\s)(?<=nand\\\\s)(?<=not\\\\s)(?<=\\\\|\\\\|)(?<=\\\\&\\\\&)\\\\w+\\\\()|(?:[\\"'`][\\\\s\\\\d]*?[^\\\\w\\\\s]+\\\\W*?\\\\d\\ ..." at ARGS_NAMES:{"heading":0.89366590976715088,"speed":24.989656448364258,"x":-33953.385528564453,"y":21.883352279663086,"z":10270.465305328369}. [file "[/etc/httpd/conf/modsecurity.d/rules/owasp_modsecurity_crs_3-plesk/REQUEST-942-APPLICATION-ATTACK-SQLI.conf](https://dsuraz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fetc%2Fhttpd%2Fconf%2Fmodsecurity.d%2Frules%2Fowasp_modsecurity_crs_3-plesk&file=REQUEST-942-APPLICATION-ATTACK-SQLI.conf&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F28)"] [line "135"] [id "942370"] [rev "2"] [msg "Detects classic SQL injection probings 2/2"] [data "Matched Data: [\\x22:0.8](https://dsuraz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%5C&file=x22%3A0.8&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F28) found within ARGS_NAMES:{\\x22heading\\x22:0.89366590976715088,\\x22speed\\x22:24.989656448364258,\\x22x\\x22:-33953.385528564453,\\x22y\\x22:21.883352279663086,\\x22z\\x22:10270.465305328369}: {\\x22heading\\x22:0.89366590976715088,\\x22speed\\x22:24.989656448364258,\\x22x\\x22:-33953.385528564453,\\x22y\\x22:21.883352279663086,\\x22z\\x22:10270.465305328369}"] [severity "CRITICA [hostname "webtoria.com"] [uri "/ir/truck/v1/truck"] [unique_id "YmJyTj-2EKs1CXHwWR@vLAAAACE"]`

I have no idea how to compile a version of this with the changes made in the last few months. Could you make a new version to see if these changes are removed? thank you

**Comment by Lihis** [comment]
Looks like your webserver is flagging the JSON to have "classic SQL injection", so this seems to be issue on your server configuration.

What comes to the Windows build, it would be nice if some one had time to fix it (I don't have a Windows machine).

**Comment by Lihis** [comment]
Created #63 to track the broken Windows build and updated [README.md](https://github.com/Lihis/ets2-job-logger#readme) to indicate that only Linux is currently supported and maintainer for Windows would be needed. As I don't have Windows (and I'm not planning to get one) to develop and test with I can't support it fully. So far the Windows build has been working nicely after it was initially setup, well at least the build has been passing on CI until the Bincrafters infrastructural changes.
