### ISSUE TITLE
Ability to add jobs

### ISSUE THREAD

**Issue by mhaque02** [Lihis/ets2-job-logger#64]
This is a feature proposal: would it be possible for a way to use this to _add_ jobs in the game? 

My VTC has some ideas where we want to have the ability to add job in the Cargo Market or Freight Market with specified routes, such as carrying logs from Frankfurt to Paris.

Would this be possible with some kind of POST request using this logger module?

**Comment by Lihis** [comment]
The Telemetery SDK which we are using allows only to receive telemetry data so it can not be used to affect anything in-game.

I don't know what kind of limitations mods would have.. or would it even be possible with mod..

If it possible with mod then the communication between the server and application needs some design as server can not make requests to client.

**Comment by Lihis** [comment]
For now closing this as out of scope for this project.
